### ISSUE TITLE
E2E tests failing

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator-go#108]
See https://github.com/laurentsimon/slsa-on-github-test/issues

The bugs above has to with entryPoint being nil, apparently introduced in https://github.com/slsa-framework/slsa-github-generator/commit/dcacbd73adc3cdddf93b0a35edf18421c8a71743

Because the e2e tests are still WIP (just a few minor updates needed), failure is reported by creating issues on a personal repo. I'll change that very soon so that there are reported in this repo, and then in slsa-github-generator when we merge the repos.

Note: I'm working on pre-submit tests that would have caught this.

@ianlewis do you want to look into this?

**Comment by laurentsimon** [comment]
I've enabled the e2e tests to create issues on this repo. I'm keeping this issue opened anyway, but we should see issues created within 24hrs

**Comment by ianlewis** [comment]
It seems like `workflow` isn't always present in the event that triggered the workflow.
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads

I'll need to see if there another way to get the path to the workflow that's being executed but there may not actually be a way to know without checking out the repo and looking for the workflow name...

I'll revert back to using `workflow` from the `github` context for now but I'll need to reopen https://github.com/slsa-framework/slsa-github-generator/issues/11

**Comment by ianlewis** [comment]
I created a pending topic on github.community to see if there is a way to reliably get the workflow path but I wonder if there aren't other avenues to submit feature requests.

**Comment by laurentsimon** [comment]
> It seems like `workflow` isn't always present in the event that triggered the workflow. https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads

the payload is not present on `schedule` events. Are there other triggers for which `workflow` is not present?

> I'll need to see if there another way to get the path to the workflow that's being executed but there may not actually be a way to know without checking out the repo and looking for the workflow name...
> 
> I'll revert back to using `workflow` from the `github` context for now but I'll need to reopen [slsa-framework/slsa-github-generator#11](https://github.com/slsa-framework/slsa-github-generator/issues/11)

**Comment by laurentsimon** [comment]
Issues have been created automatically. I pushed https://github.com/slsa-framework/slsa-github-generator-go/pull/111 and updated the go.mod, and it's breaking the e2e tests again because the API has changed (https://github.com/slsa-framework/slsa-github-generator/pull/45). I'll look into it.

It's good to validate it got caught.

**Comment by ianlewis** [comment]
> the payload is not present on `schedule` events. Are there other triggers for which `workflow` is not present?

Yeah, it's unfortunately missing on most events. I mistakenly thought it was a common field. I can't really see why it can't be on most events but I suppose `github.workflow` will satisfy most use cases. In our case we really want the path so we can get a unique entrypoint.

It seems you can query the action run via the Github API and figure out the workflow path from there.
https://github.community/t/getting-the-path-to-user-workflow-yaml-from-reusable-workflow/250514/2

**Comment by laurentsimon** [comment]
Closing since this it fixed.
