### ISSUE TITLE
The name of this repository looks a bit misleading

### ISSUE THREAD

**Issue by marcofranssen** [slsa-framework/slsa-github-generator-go#13]
I interpreted this repository as a go commandline tool to generate a GitHub workflow boilerplate.

- Is it a code generator?
- Is it provenance?
- Is it an example using Go?
- …

**Comment by laurentsimon** [comment]
If you have no further comment, shall I close this issue?

**Comment by laurentsimon** [comment]
We're going to merge the code into https://github.com/slsa-framework/slsa-github-generator.
Closing
