### ISSUE TITLE
Feature: Use new APIs

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator-go#37]
Move to the new APIs defined in https://github.com/slsa-framework/slsa-github-generator

**Comment by laurentsimon** [comment]
@ianlewis when do you think we should attempt a "migration" to the new API? What are the main blockers we should address before attempting it? (I think we want to do the migration before the first v1 release on this repo; but let us know if you think that's a bad idea)

I ask because the 2 implementation may start drifting away or duplicate effort, e.g., https://github.com/slsa-framework/slsa-github-generator-go/pull/16 is a tracking issue in both repos.

**Comment by ianlewis** [comment]
Yeah, I think we can start now but we will want to solidify the API of both and release both together for v1. We just need to keep in mind that some (hopefully small) changes to the API may happen in the meantime.

**Comment by ianlewis** [comment]
On, the flip side, if there is missing functionality in the slsa-github-generator API that we need, please make sure we have an issue for it in that repo. I think we've covered most things already but just a reminder.
