### ISSUE TITLE
Feature: Support building and releasing binaries for multiple OSs

### ISSUE THREAD

**Issue by ddworken** [slsa-framework/slsa-github-generator-go#51]
I'm currently using `slsa-github-generator-go` to build and release [hishtory](https://github.com/ddworken/hishtory) binaries so that users can verify their provenance. Currently I'm using this to build [linux-amd64 binaries](https://github.com/ddworken/hishtory/blob/7ea6427/.slsa-goreleaser.yml#L6-L7), but I'd like to release binaries for darwin-amd64 and darwin-arm too. As far as I can tell, this isn't possible (other than by repeatedly modifying `.slsa-goreleaser.yml`). 

Would it be possible to support this? I'm imagining that `.slsa-goreleaser.yml` could be something like:

```
[](https://github.com/)version: 1

flags:
  - -trimpath

goos: 
  - linux
  - darwin
goarch: 
  - amd64
  - arm64

binary: hishtory-{{ .OS }}-{{ .Arch }}

ldflags:
  - '{{ .Env.VERSION_LDFLAGS }}'
```

**Comment by laurentsimon** [comment]
Agreed we need this. We were thinking of tackling it in slsa-framework/slsa-github-generator#63, but I think your proposal works just fine.

I'm curious which project you're releasing provenance for?

**Comment by ddworken** [comment]
Ah whoops, sorry, I misunderstood that issue when searching for duplicates. Closing as a duplicate. 

I'm experimenting with SLSA for `hishtory` which is a tool for cross-platform encrypted sync of shell history and associated metadata. Currently I'm using it for initial install and for [secure updates](https://github.com/ddworken/hishtory/blob/master/client/lib/lib.go#L472-L521). If you're curious, I also [hacked together my own support for building multiple binaries](https://github.com/ddworken/hishtory/commit/4036a4594b9b5941ed5c2212cb61583d5f50ae8c).

**Comment by laurentsimon** [comment]
Thanks for sharing your code. I was super curious how you did it!
