### ISSUE TITLE
Ubuntu doesn't come with jq

### ISSUE THREAD

**Issue by naveensrinivasan** [slsa-framework/slsa-github-generator-go#53]
https://github.com/slsa-framework/slsa-github-generator-go/blob/2647f67d8110e1e4a3fdc2f76020a60a33191497/.github/workflows/builder.yml#L73

☝️  line refers to `jq` command which doesn't come with ubuntu. 

Am I missing something?

**Comment by naveensrinivasan** [comment]
cc @laurentsimon

**Comment by laurentsimon** [comment]
does not come with the ubuntu distribution or with the `ubuntu-latest` GitHub uses for its runners? Is the code above failing in your workflow runs?

**Comment by naveensrinivasan** [comment]
> does not come with the ubuntu distribution or with the `ubuntu-latest` GitHub uses for its runners? Is the code above failing in your workflow runs?

I didn't test it in the runner. I tested in my own ubuntu. Need to test it in the runner.

**Comment by laurentsimon** [comment]
Let me know when you've tested and we'll close this issue.

**Comment by laurentsimon** [comment]
Since the workflows work, I assume we can close it. Re-open if needed
