### ISSUE TITLE
Trust on builder - SolarWinds attack vector.

### ISSUE THREAD

**Issue by naveensrinivasan** [slsa-framework/slsa-github-generator-go#55]
1. https://github.com/slsa-framework/slsa-github-generator-go/blob/87c137ee22e721fb019f2b9408044ece67a0dd5a/.github/workflows/builder.yml#L122

2. https://github.com/slsa-framework/slsa-github-generator-go/blob/87c137ee22e721fb019f2b9408044ece67a0dd5a/.github/workflows/builder.yml#L123

Could the builder binary be replaced by the trojan binary by something like a SolarWinds attack? 

Something like https://github.com/testifysec/solarsploit#solarsploit

Either by pausing the go [compiler](https://github.com/testifysec/solarsploit#solarsploit) or the attack vector waiting for a syscall to `sha256sum` and replacing the binary with the trojan binary between steps 1 and 2.

How can someone trust the builder in this case?

**Comment by naveensrinivasan** [comment]
@laurentsimon  FYI...

**Comment by laurentsimon** [comment]
If the builder itself is compromised, all bets are off. The only way to protect against builder compromise is to vary the builder, e.g. having different builders compare their output, i.e. reproducible builds.

I think this is discussed in https://github.com/slsa-framework/slsa/issues/362

**Comment by naveensrinivasan** [comment]
> If the builder itself is compromised, all bets are off. The only way to protect against builder compromise is to vary the builder, e.g. having different builders compare their output, i.e. reproducible builds.
> 
> I think this is discussed in [slsa-framework/slsa#362](https://github.com/slsa-framework/slsa/issues/362)

Agreed, multiple builders, and have reproducible builds. Thanks

**Comment by laurentsimon** [comment]
Closing the issue then. Re-open if needed.
