### ISSUE TITLE
Feature: support for releasing as assets

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator-go#58]
It may be useful to provide an option for users to release the provenance and artifacts as assets to a GitHub release, like goreleaser does.

It's possible for users to do that themselves, but when multiple builds are generated, it becomes more cumbersome for users to do it themselves. Goreleaser offers such an option, for example

**Comment by joshuagl** [comment]
💯 

For most (all?) ecosystems the question of where to publish provenance is still unanswered. We should encourage folks to upload them to the release pages on GitHub. This will make even more sense for non-Go ecosystems (where release artefacts are more frequently fetched and used).
